# Generated by Django 2.1.1 on 2018-09-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
