# Generated by Django 2.1 on 2018-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0004_auto_20180816_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='slide',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='categorycarousel',
            name='slide',
            field=models.ImageField(blank=True, null=True, upload_to='categorycarousel'),
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='categorylist'),
        ),
        migrations.AlterField(
            model_name='categorylistimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='categorylistimages'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
