# Generated by Django 2.1 on 2018-08-20 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0007_carousel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorylist',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
