# Generated by Django 2.1 on 2018-08-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0008_auto_20180820_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylistimages',
            old_name='list',
            new_name='item',
        ),
    ]
