# Generated by Django 2.1 on 2018-08-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0009_auto_20180821_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='categorycarousel',
            name='active_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='showing_mainpage_carousel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.CategoryList'),
        ),
        migrations.AddField(
            model_name='videos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
    ]
