# Generated by Django 2.1 on 2018-08-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0016_remove_categorycarousel_active_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
