# Generated by Django 2.1 on 2018-08-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0017_auto_20180828_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='acknowledge',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='registers',
            name='acknowledge_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AlterField(
            model_name='registers',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
