# Generated by Django 2.1 on 2018-08-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0018_auto_20180828_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='acknowledge',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
