# Generated by Django 2.1 on 2018-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0021_auto_20180830_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
