# Generated by Django 2.1 on 2018-08-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0022_registers_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
