# Generated by Django 2.1 on 2018-09-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0023_categorylist_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
