# Generated by Django 2.1 on 2018-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0024_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='categorylist_bannerimage'),
        ),
    ]
