# Generated by Django 2.1 on 2018-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0025_categorylist_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='internal_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='internal_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorycarousel',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorycarousel',
            name='internal_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorylistimages',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorylistimages',
            name='internal_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
