# Generated by Django 2.1 on 2018-09-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0026_auto_20180903_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onorapp.Categories'),
        ),
    ]
