# Generated by Django 2.1.1 on 2018-09-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0003_auto_20180914_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.BooleanField(choices=[(True, 'paid'), (False, 'not_paid')], default=False),
        ),
    ]
