# Generated by Django 2.1.1 on 2018-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0004_auto_20180914_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'paid'), ('n', 'not_paid')], default='np', max_length=1),
        ),
    ]
