# Generated by Django 2.1.1 on 2018-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0008_auto_20180914_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('not_paid', 'not_paid')], default='not_paid', max_length=10),
        ),
    ]
