# Generated by Django 2.1.1 on 2018-09-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0009_auto_20180914_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='partial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
