# Generated by Django 2.1.1 on 2018-09-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billpay', '0012_auto_20180915_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billpay.payments')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_credits',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billpay.transactions'),
        ),
        migrations.AddField(
            model_name='user_credits',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='billpay.users'),
        ),
    ]
