# Generated by Django 2.0.7 on 2018-07-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopItems', '0002_auto_20180717_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
