# Generated by Django 2.1.1 on 2018-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('posted_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
