# Generated by Django 2.1 on 2018-09-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
