# Generated by Django 2.1 on 2018-09-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
            ],
        ),
    ]
