# Generated by Django 2.1 on 2018-08-11 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carosuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(blank=True, null=True, upload_to='image1')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image2')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCarosuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(blank=True, null=True, upload_to='image3')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='image4')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryListImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='image5')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.CategoryList')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageCarosuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carosuelname', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('emailId', models.EmailField(blank=True, default='', max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='mainpagecarosuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AddField(
            model_name='categorylistimages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AddField(
            model_name='categorycarosuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AddField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
        migrations.AddField(
            model_name='carosuel',
            name='carosuelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.MainPageCarosuel'),
        ),
        migrations.AddField(
            model_name='carosuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onorapp.Users'),
        ),
    ]
