# Generated by Django 2.1 on 2018-08-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0005_auto_20180817_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagecarousel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carouselname',
        ),
        migrations.DeleteModel(
            name='MainPageCarousel',
        ),
    ]
