# Generated by Django 2.1 on 2018-08-10 10:27

import Catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.ImageField(blank=True, null=True, upload_to=Catalog.models.carosule_file_name)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='categorie_curosels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.ImageField(blank=True, null=True, upload_to=Catalog.models.cat_file_name)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('mobile_no', models.CharField(max_length=20)),
                ('pics', models.ImageField(blank=True, null=True, upload_to=Catalog.models.new_file_name)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to=Catalog.models.item_file_name)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_Of_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Banner', models.ImageField(blank=True, null=True, upload_to=Catalog.models.list_file_name)),
                ('Address', models.TextField()),
                ('Description', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='mainpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
        migrations.AddField(
            model_name='list_of_items',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
        migrations.AddField(
            model_name='item_pics',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.List_Of_Items'),
        ),
        migrations.AddField(
            model_name='item_pics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
        migrations.AddField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
        migrations.AddField(
            model_name='categorie_curosels',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Categories'),
        ),
        migrations.AddField(
            model_name='categorie_curosels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
        migrations.AddField(
            model_name='carousels',
            name='mainpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.MainPage'),
        ),
        migrations.AddField(
            model_name='carousels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.Users'),
        ),
    ]
