# Generated by Django 2.1 on 2018-08-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='change',
            field=models.IntegerField(default=0),
        ),
    ]
