# Generated by Django 2.1 on 2018-08-20 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0006_auto_20180818_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
