# Generated by Django 2.1 on 2018-08-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0010_auto_20180822_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylist',
            old_name='showing_mainpage_carousel',
            new_name='show_in_mainpage_carousel',
        ),
    ]
