# Generated by Django 2.1 on 2018-08-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0011_auto_20180822_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='show_in_mainpage',
            field=models.BooleanField(default=True),
        ),
    ]
