# Generated by Django 2.1 on 2018-08-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0015_auto_20180827_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycarousel',
            name='active_show',
        ),
    ]
