# Generated by Django 2.1 on 2018-08-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0019_auto_20180829_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorylist',
            old_name='url',
            new_name='external_url',
        ),
        migrations.AddField(
            model_name='categorylist',
            name='internal_url',
            field=models.URLField(blank=True),
        ),
    ]
