# Generated by Django 2.1 on 2018-09-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onorapp', '0022_categorylist_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onorapp.Categories'),
        ),
    ]
